### ISSUE TITLE
Featue: Roadmap

### ISSUE THREAD

**Issue by tada5hi** [dnpm-dip/portal#1]
Essentials
- [x] ci/cd pipeline
- [x] linter, monorepo management ( lerna/changesets) 
- [x] types/interfaces for domain resources: patient, consent, case, ....
- [x] api client for resources
- [x] interaction between `rare-deseases` and `portal` (ink. navigation, pages, api client ...)
- [x] basic styling 
- [x] layout navigation
- [x] outsource reusable components, composables, ... to extra package (core)
- [x] pages for rd search, query, patient-record
- [ ] lazy load single resources ( template slot for loading )
- [ ] unify loading and rendering of single/collection resources
- [ ] enhance styling, usability, pages
- [ ] implement features
- [ ] docker image for cd
